# Generated by Django 5.2 on 2025-05-02 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_passwordresetcode_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 16, 34, 10, 848156), editable=False),
        ),
    ]
