# Generated by Django 5.2 on 2025-05-09 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_passwordresetcode_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 19, 20, 45, 843943), editable=False),
        ),
    ]
