# Generated by Django 5.2 on 2025-05-10 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_passwordresetcode_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 12, 42, 6, 736158), editable=False),
        ),
    ]
